# 内置工具配置
serper_dev_tool:
  name: "Serper 搜索工具"
  description: "用于搜索最新的市场新闻和公司信息"
  api_key: "${SERPER_API_KEY}"

scrape_website_tool:
  name: "网站内容抓取工具"
  description: "抓取指定网站的内容进行分析"

# 自定义工具配置
# yfinance_tool:
#   name: "雅虎财经数据工具"
#   description: "获取股票的财务数据、价格数据和历史数据"
#   module: "src.tools.financial_tools"
#   class: "YFinanceTool"

# 使用AkShare替换YFinance
akshare_tool:
  name: "AkShare数据工具"
  description: "获取A股股票的财务数据、价格数据和历史数据"
  module: "src.tools.akshare_tools"
  class: "AkShareTool"

financial_calculator_tool:
  name: "金融计算器工具"
  description: "计算各种财务指标和比率"
  module: "src.tools.financial_tools"
  class: "FinancialCalculatorTool"

technical_analysis_tool:
  name: "技术分析工具"
  description: "计算技术指标和分析价格走势"
  module: "src.tools.technical_tools"
  class: "TechnicalAnalysisTool"

charting_tool:
  name: "图表生成工具"
  description: "生成股票价格和技术分析图表"
  module: "src.tools.charting_tools"
  class: "ChartingTool"

fundamental_analysis_tool:
  name: "基本面分析工具"
  description: "进行公司基本面价值评估"
  module: "src.tools.fundamental_tools"
  class: "FundamentalAnalysisTool"

risk_assessment_tool:
  name: "风险评估工具"
  description: "评估各类投资风险"
  module: "src.tools.risk_tools"
  class: "RiskAssessmentTool"

industry_analysis_tool:
  name: "行业分析工具"
  description: "分析行业竞争格局和发展趋势"
  module: "src.tools.industry_tools"
  class: "IndustryAnalysisTool"

report_writing_tool:
  name: "报告编写工具"
  description: "生成标准化的分析报告"
  module: "src.tools.reporting_tools"
  class: "ReportWritingTool"

data_validation_tool:
  name: "数据验证工具"
  description: "验证数据准确性和完整性"
  module: "src.tools.data_tools"
  class: "DataValidationTool"

sentiment_analysis_tool:
  name: "情绪分析工具"
  description: "分析市场情绪和新闻情绪"
  module: "src.tools.sentiment_tools"
  class: "SentimentAnalysisTool"

# 工具分组配置
market_research_tools:
  - serper_dev_tool
  - scrape_website_tool
  - akshare_tool
  - sentiment_analysis_tool

financial_analysis_tools:
  - akshare_tool
  - financial_calculator_tool
  - data_validation_tool

technical_analysis_tools:
  - technical_analysis_tool
  - charting_tool

analysis_tools:
  - fundamental_analysis_tool
  - risk_assessment_tool
  - industry_analysis_tool

reporting_tools:
  - report_writing_tool
  - charting_tool

validation_tools:
  - data_validation_tool
  - sentiment_analysis_tool